### ISSUE TITLE
Xprinter xp-420B

### ISSUE THREAD

**Issue by PhamChuongBD** [thiendangit/react-native-thermal-receipt-printer-image-qr#13]
Chào bạn @thiendangit .

Mình có thứ với áy in xprinter 420 , sau khi kết nối thành công , mình có in test nhưng không ra bill . Mình không biết lib có hỗ trợ xprinter không. Xin cảm ơn.

**Comment by thiendangit** [comment]
@PhamChuongBD bạn in bằng LAN hả ?

**Comment by PhamChuongBD** [comment]
> @PhamChuongBD bạn in bằng LAN hả ?

Mình thư cả LAN và BLE , đều không được

**Comment by thiendangit** [comment]
@PhamChuongBD mình fork từ thư viện react-native-thermal-receipt-printer! có thể thư viện không hổ trợ máy in xprinter của bạn

**Comment by thiendangit** [comment]
@PhamChuongBD với LAN bạn đã connect thành công chưa ?

**Comment by PhamChuongBD** [comment]
Mình kết nối thành công hết nha, nhưng gửi lệnh in máy in nháy đèn thôi , chứ ko ra giấy

**Comment by thiendangit** [comment]
Don't support direct thermal barcode printer

**Comment by hoanganhnh2009** [comment]
> Close - Don't support direct thermal barcode printer

Nope, i can printer with direct thermal barcode printer with this module. If you need can contact me.
