### ISSUE TITLE
Got an error when I build in ios

### ISSUE THREAD

**Issue by Rogax** [thiendangit/react-native-thermal-receipt-printer-image-qr#132]
When i build my code by Xcode:
Building for 'iOS-simulator', but linking in object file (/Users/cuongnv/Work/src/1erp-pos-app-reactnative/node_modules/react-native-thermal-receipt-printer-image-qr/ios/PrinterSDK/libPrinterSDK.a[arm64][2](GCDAsyncSocket.o)) built for 'iOS'
Any solution?
![image](https://github.com/user-attachments/assets/77702e27-df55-4e0f-8075-83a881a2877c)

**Comment by vinibgoulart** [comment]
How do you fixed this? I'm having the same issue here https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr/issues/134

**Comment by Rogax** [comment]
Sorry for the delay.
Add this code in Podfile:
`installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end`
And setting like this in Xcode:
![Image](https://github.com/user-attachments/assets/4a4b4ab8-3521-4611-b9b5-413b9ed3b832)
