### ISSUE TITLE
Error Building for 'iOS-simulator' React native 0.76

### ISSUE THREAD

**Issue by tanthuan031** [thiendangit/react-native-thermal-receipt-printer-image-qr#134]
When i build my code by Xcode:
Building for 'iOS-simulator', but linking in object file (/Users/cuongnv/Work/src/1erp-pos-app-reactnative/node_modules/react-native-thermal-receipt-printer-image-qr/ios/PrinterSDK/libPrinterSDK.a[arm64][2](https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr/issues/GCDAsyncSocket.o)) built for 'iOS'

Any solution?

**Comment by richardfariax** [comment]
I have the same problem

**Comment by vinibgoulart** [comment]
same problem here, was there some breaking change in xcode or ios version updates? cc @thiendangit

**Comment by tanthuan031** [comment]
> I have the same problem



> same problem here, was there some breaking change in xcode or ios version updates? cc @thiendangit



> I have the same problem

Hello I fixed it

Step 1

![image](https://github.com/user-attachments/assets/2d873e64-50ae-4a04-a40f-10a27deebb31)


Step 2 add code 
================
 installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
===============
![image](https://github.com/user-attachments/assets/c95f7020-81be-435d-96d3-3ba23281ce7a)

**Comment by richardfariax** [comment]
Not working
