### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by DanielBillon** [thiendangit/react-native-thermal-receipt-printer-image-qr#14]
Hello, when I use:
 USBPrinter.init().then(()=> {
      //list printers
      USBPrinter.getDeviceList().then(setPrinters);
    }
I get this alert message:
![Capture1](https://user-images.githubusercontent.com/52280149/146409526-31c4ffdc-a274-43ac-8213-fe75c92c52df.PNG)

**Comment by thiendangit** [comment]
@DanielBillon tks your feedback! I’ll check it asap

**Comment by thiendangit** [comment]
@DanielBillon This error appeared in react-native version from 0.66.
You can fix it quickly by:  
go to dist -> index.js-> line 436 -> change this  line 
var NetPrinterEventEmitter = new NativeEventEmitter(RNNetPrinter);
to 
var NetPrinterEventEmitter = new NativeEventEmitter();

**Comment by DanielBillon** [comment]
@thiendangit  super problem solved. Thank you
