### ISSUE TITLE
feat: Can we have a method to print PDF ?

### ISSUE THREAD

**Issue by nishit-g** [thiendangit/react-native-thermal-receipt-printer-image-qr#17]
- We can have a method where we can pass local pdf or remote pdf URL and print it.

I would love to help, just don't know how to move ahead w/ this.

**Comment by thiendangit** [comment]
i think you render pdf to react native view and capture this to print! 
Now i think this lib can't support print pdf
<img width="704" alt="Screen Shot 2021-12-27 at 17 18 34" src="https://user-images.githubusercontent.com/56025627/147462236-dcbed8ff-40fa-45b2-a527-adaa24dd07b8.png">

**Comment by nishit-g** [comment]
Hey @thiendangit , how about we convert the pdf to image and try to print it out ? will this work ?

**Comment by thiendangit** [comment]
@nishit-g you can using react-native-screen-shot! but printing with image will be slowly than text

**Comment by nishit-g** [comment]
Thanks a lot @thiendangit , will try it out.
