### ISSUE TITLE
Cannot cut the paper

### ISSUE THREAD

**Issue by hoangdt224** [thiendangit/react-native-thermal-receipt-printer-image-qr#20]
I cannot cut the bill when I calling printer like that:
 NetPrinter.printBill(textForPrinting, {
          cut: false,
          tailingLine: false,
        });
        NetPrinter.printImageBase64(sign, {
          cut: true,
          tailingLine: false,
        });

**Comment by thiendangit** [comment]
@hoangdt224 NetPrinter.printBill will be auto cut => you can using printText
 NetPrinter.printImageBase6 don't support cut! you can using printText(..., {cut : true}) or printBill to cut

**Comment by hoangdt224** [comment]
I've tried to use printBill/printText after printImageBase64, but it didn't work. 
Cause I want to print the order and signature in the  same bill.

**Comment by thiendangit** [comment]
@hoangdt224 https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr/blob/24a5d006c4c5929949d27a8337373a5ba79f3616/example/src/HomeScreen.tsx#L217! have you tried this?

**Comment by hoangdt224** [comment]
Thank you very much,
It fixed <3
