### ISSUE TITLE
Is there any option for the print preview ? 

### ISSUE THREAD

**Issue by jagruticodoffer** [thiendangit/react-native-thermal-receipt-printer-image-qr#22]
Currently, I'm printing invoice, when i print it will change the sequence of the order lines. So if is there any option to show the preview before print then, it will save some papers. Any suggestion related to this will be accepted.

**Comment by thiendangit** [comment]
You can use react native view to show it to the user! if you change the sequence of the order lines you also need to update the react native view interface!

**Comment by thiendangit** [comment]
@jagruticodoffer You can use react native view to show it to the user! if you change the sequence of the order lines you also need to update the react native view interface!
