### ISSUE TITLE
Support for printer codepage to support VietNamese?

### ISSUE THREAD

**Issue by levantanphat9c** [thiendangit/react-native-thermal-receipt-printer-image-qr#23]
Hi thiendangit,

Could you help me print text Vietnamese?

Thank you!

**Comment by thiendangit** [comment]
@levantanphat9c you can remove the mark : Tiếng việt =>Tieng viet!

**Comment by thuytony** [comment]
I need to print invoices in Vietnamese. I looked for some solutions but in the end, I found that the printer does not support Vietnamese. Do you have any solution for this? How can I print in Vietnamese?

**Comment by levantanphat9c** [comment]
You can sendRawData turn off Chinese Character and set codepage VN.

But i have a problem with this. This is Lý Chính Thắng change to Lã Ch anh Th   ương

**Comment by thuytony** [comment]
How can I do this? Can you give me more detail to do this?

**Comment by levantanphat9c** [comment]
const VIE_LANGUAGE = '\x1b\x74\x27'; //x27 => codePage VN in model printer, you can replace it
        const CHINESE_OFF = '\x1c\x2e';
        const SET_INTERNATIONAL_CHARACTER = '\x1b\x52\x12';

        NetPrinter.printText(
          `${CHINESE_OFF}${VIE_LANGUAGE}${SET_INTERNATIONAL_CHARACTER}${BOLD_ON}(Đơn tạm tính)${BOLD_OFF}`,
        );
        
        
        You can try.

**Comment by levantanphat9c** [comment]
you can print selft test on your printer

**Comment by dvquoc** [comment]
> you can print selft test on your printer

my codePage in the model is P27 (Vietnam). when converted to... how does it look like?

**Comment by thuytony** [comment]
Hello guys. After some time searching, I found that my printer can't print the Vietnamese language. So I'm using image printing instead of text printing :D
