### ISSUE TITLE
Adjusting font size

### ISSUE THREAD

**Issue by okumujustine** [thiendangit/react-native-thermal-receipt-printer-image-qr#28]
Is it possible to adjust the font size?

**Comment by thiendangit** [comment]
@okumujustine you can try to add this one : 
COMMANDS.TEXT_FORMAT.TXT_4SQUARE or
COMMANDS.TEXT_FORMAT.TXT_2.WIDTH 
```js
const {TXT_2WIDTH} = COMMANDS.TEXT_FORMAT
await Printer.printText(`${TXT_2WIDTH} Bill`);
```
