### ISSUE TITLE
yarn bootstrap issue

### ISSUE THREAD

**Issue by bklutse20** [thiendangit/react-native-thermal-receipt-printer-image-qr#29]
Can someone help me understand and resolve this issue. Anytime I run yarn bootstrap it throws the below error.

error Couldn't find match for "3d2d79c6d9e748dc8296a8524a36fdc604c429c6" in "refs/heads/main,refs/heads/v0.1.7,refs/tags/main,refs/tags/v0.1.2,refs/tags/v0.1.3,refs/tags/v0.1.4,refs/tags/v0.1.6,refs/tags/v1.0.2" for "https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Youssef-Durgham** [comment]
what the solve please ?

**Comment by OhFarhan** [comment]
solution @bklutse20
