### ISSUE TITLE
Styling image

### ISSUE THREAD

**Issue by bklutse20** [thiendangit/react-native-thermal-receipt-printer-image-qr#30]
Can anyone kindly help me on how to add some more styles to Printer.printImage. I will love to apply some width, height and position the image. How do I achieve this please.

**Comment by thiendangit** [comment]
@bklutse20 you can refer to this link: https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr/issues/21#issuecomment-1005654475

**Comment by bklutse20** [comment]
@thiendangit thank you so much for your help. Does this mean all image sizes in the application will be affected? How do I apply to a particular image?

**Comment by thiendangit** [comment]
@bklutse20 it comes out in the next version when i have time!

**Comment by bklutse20** [comment]
Hi @thiendangit 

I also have issues using images in my local project. It says image not found but works when I use an online image. Can you support this please.

**Comment by thiendangit** [comment]
@bklutse20 you can try to coverrt local image to base64 : 
https://www.npmjs.com/package/react-native-image-base64
and using function printImageBase64

**Comment by bklutse20** [comment]
Thank you very much brother. I really appreciate your support.

**Comment by thiendangit** [comment]
@bklutse20 try to using v0.1.8! i added width, height, padding X for image
