### ISSUE TITLE
imageWidth, imageHeight, print center

### ISSUE THREAD

**Issue by AnneJackal** [thiendangit/react-native-thermal-receipt-printer-image-qr#37]
Hello,
I have two questions. I'm using version 0.1.8.
1. imageWidth and imageHeight in printImageBase64 and printImage settings are small, but when its come out it looks much bigger size. How do we print small size? 
We are testing on Android.
2. How to display the printed image and qrcode in the center? Now its printing on the left side 
Thank you. 
BR,

**Comment by thiendangit** [comment]
have you try this : ```js
Printer.printImage('https://media-cdn.tripadvisor.com/media/photo-m/1280/1b/3a/bd/b5/the-food-bill.jpg', {
imageWidth: 100,
})
```

**Comment by AnneJackal** [comment]
yes i tried seen in three ways below:
 - BLEPrinter.printImage(imageUrl, { imageWidth: 100,  imageHeight: 100  });
 - BLEPrinter.printImage(imageUrl, { imageWidth: 100  });
 - BLEPrinter.printImage(imageUrl, { imageHeight: 100  });

**Comment by thiendangit** [comment]
@AnneJackal let me check!

**Comment by thiendangit** [comment]
@AnneJackal please try again with v1.0.9

**Comment by thiendangit** [comment]
No response!

**Comment by AnneJackal** [comment]
It works :) Thank you so much
