### ISSUE TITLE
App carshed as soon I install this library

### ISSUE THREAD

**Issue by shaikhhafizf** [thiendangit/react-native-thermal-receipt-printer-image-qr#38]
As soon as I installed this library, my app was crashed only a blank screen was showing.
To run my app again, I needed to delete this library manually because It is not uninstalling by a command also.

I loved the features of this library but want able to install it properly. Can anyone give me a solution?

**Comment by thiendangit** [comment]
https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr#troubleshoot

**Comment by shaikhhafizf** [comment]
> https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr#troubleshoot

did  this but didn't work

**Comment by shaikhhafizf** [comment]
Got solution

It solves by removing the 'react-native-thermal-printer' library from the yarn or project.
