### ISSUE TITLE
error install react native  0.67

### ISSUE THREAD

**Issue by Fharhanamrin** [thiendangit/react-native-thermal-receipt-printer-image-qr#42]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myblutooth_build_newplugin_apk2@0.0.1
Solids-MacBook-Pro:MyBlutooth_build_newplugin_apk2 smi$ npm i react-native-thermal-receipt-printer-image-qr
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myblutooth_build_newplugin_apk2@0.0.1
npm ERR! Found: react-native@0.67.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.67.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2 || ^0.57.0" from react-native-ping@1.2.6
npm ERR! node_modules/react-native-ping
npm ERR!   peer react-native-ping@"*" from react-native-thermal-receipt-printer-image-qr@0.1.9
npm ERR!   node_modules/react-native-thermal-receipt-printer-image-qr
npm ERR!     react-native-thermal-receipt-printer-image-qr@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/smi/.npm/eresolve-report.txt for a full report.

**Comment by thiendangit** [comment]
you can try that : https://stackoverflow.com/questions/64936044/fix-the-upstream-dependency-conflict-installing-npm-packages
