### ISSUE TITLE
could not install  react-native-thermal-receipt-printer-image-qr

### ISSUE THREAD

**Issue by chukiatt** [thiendangit/react-native-thermal-receipt-printer-image-qr#44]
Hi  thiendangit

Are you remember me. i am chukiat in thailand that you help to dev this library for help me to print image and qr
After developed POS app until almost there success and then to use your library to print image for receipt. 
But i got error when install your new release like that. 
Please help me again. 
Thank you very much. Thiendangit

D:\Source\2019\ReactNative\posware-printing> **npm i react-native-thermal-receipt-printer-image-qr**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-project@0.0.1
npm ERR! Found: react-native@0.66.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.66.3" from the root project
npm ERR!
**npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2 || ^0.57.0" from react-native-ping@1.2.6**
npm ERR! node_modules/react-native-ping
npm ERR!   peer react-native-ping@"*" from react-native-thermal-receipt-printer-image-qr@0.1.9
npm ERR!   node_modules/react-native-thermal-receipt-printer-image-qr
npm ERR!     react-native-thermal-receipt-printer-image-qr@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by thiendangit** [comment]
@chukiatt let me check !

**Comment by thiendangit** [comment]
@chukiatt 
Two ways:

1. npm install <package-name> --legacy-peer-deps
2. install Recommended node version for most users

The better way is to install the recommended version of node to work for all packages.

**Comment by chukiatt** [comment]
Thank you very much @thiendangit 
I hope you enjoy your work.

**Comment by thiendangit** [comment]
@chukiatt you too !!!
