### ISSUE TITLE
Print local image

### ISSUE THREAD

**Issue by rohitatcoffee** [thiendangit/react-native-thermal-receipt-printer-image-qr#45]
Is there any way to print local images? I tried converting the image to base64 but the printer is printing garbage data. But I passed image link then it get printed.

**Comment by thiendangit** [comment]
@rohitatcoffee please try to using this function : printImageBase64

**Comment by rohitatcoffee** [comment]
> @rohitatcoffee please try to using this function : printImageBase64

Yes, I tried that one too. printImageBase64 only taking base64 data not local image URI

**Comment by thiendangit** [comment]
you can using this lib to capture ->  covert to base64-> print
https://github.com/gre/react-native-view-shot

**Comment by rohitatcoffee** [comment]
I am doing the following things,

1. Render data in Webview
2. Capture screenshots using https://github.com/gre/react-native-view-shot
3. Then convert screenshot to base64 using react-native-fs and print using `Printer.printImageBase64(res, { beep: false, imageWidth:600});`

But still getting messed up data. 

[https://i.ibb.co/hf3JKqg/20220407-183129.jpg](url)

**Comment by thiendangit** [comment]
maybe your base64 is wrong! 
try this : https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr/blob/54b4ec997a4319ca4a330d85523cf9393cbd242d/example/src/HomeScreen.tsx#L191

**Comment by rohitatcoffee** [comment]
@thiendangit I am able to solve this issue, the issue was the width. I was passing images with the wrong dimensions.

**Comment by yaser-elbatal** [comment]
> @thiendangit I am able to solve this issue, the issue was the width. I was passing images with the wrong dimensions.

what is the best dimensions?

**Comment by OhFarhan** [comment]
if you are printing in a small printer use image width less than 200 or 300 @rohitatcoffee

**Comment by Tiepbm** [comment]
Hi @OhFarhan , 
i am using 80mm thermal printer, i try to print image from react-native-view-shot with size 576 but i dont see the image printed
```
const imageBase64 = await captureRef(invoiceRef, {
                format: 'jpg',
                quality: 1,
                result: 'base64',
            });
            const cleanBase64 = imageBase64.replace(/^data:image\/jpeg;base64,/, '').replace(/(\r\n|\n|\r)/gm, '');
            if(cleanBase64?.length==0)   Alert.alert('Lỗi Base 64');
            const BOLD_ON = COMMANDS.TEXT_FORMAT.TXT_BOLD_ON;
            const BOLD_OFF = COMMANDS.TEXT_FORMAT.TXT_BOLD_OFF;

            const CENTER = COMMANDS.TEXT_FORMAT.TXT_ALIGN_CT;
            const Printer = printerList[selectedValue];
            Printer.printText(`${CENTER}${BOLD_ON} NOI BAI AIRPORT SERVICES JOINT STOCK COMPANY${BOLD_OFF}`);
            Printer.printImageBase64(cleanBase64, {
                    imageWidth: 576,
                    imageHeight: 600,
            });
            Printer.printBill(`${CENTER}Thank you\n`, {beep: false});
```
this is my base64 image information

![Image](https://github.com/user-attachments/assets/48ae379a-e9df-4cc6-9320-5fb952a2e6dd)
