### ISSUE TITLE
How to print Chinese language ?

### ISSUE THREAD

**Issue by ponleukea** [thiendangit/react-native-thermal-receipt-printer-image-qr#49]
I want to print receipt with Chinese language.

**Comment by thiendangit** [comment]
If you just using for android you can using this lib : esc-pos-encoder.
this is example code : https://github.com/thiendangit/react-native-thermal-receipt-printer-image-qr/blob/54b4ec997a4319ca4a330d85523cf9393cbd242d/example/src/HomeScreen.tsx#L231
