### ISSUE TITLE
Error Build Release IOS architecture armv7

### ISSUE THREAD

**Issue by nguyenthanhtruongntt85** [thiendangit/react-native-thermal-receipt-printer-image-qr#52]
Error Build Release IOS architecture armv7

Bitcode bundle could not be generated because ‘node_modules/react-native-thermal-receipt-printer-image-qr/ios/PrinterSDK/libPrinterSDK.a(GCDAsyncSocket.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file ‘node_modules/react-native-thermal-receipt-printer-image-qr/ios/PrinterSDK/libPrinterSDK.a' for architecture armv7

**Comment by thiendangit** [comment]
Have you tried Enable bitcode = NO?

**Comment by nguyenthanhtruongntt85** [comment]
> Have you tried Enable bitcode = NO?

No, default bitcode is enable.
if bitcode enable then build release will error.

**Comment by nguyenthanhtruongntt85** [comment]
Note: libPrinterSDK.a build with mode disable bitcode.
All project default is enable bitcode.
So, if bitcode enable then build release will error.
if disable bitcode of project then build will no error.

**Comment by nguyenthanhtruongntt85** [comment]
> > Have you tried Enable bitcode = NO?
> 
> No, default bitcode is enable. if bitcode enable then build release will error.

you can't fix, right?

**Comment by thiendangit** [comment]
@nguyenthanhtruongntt85 I fork this for my quickly project, this is not the official project and now i don't have time to support for you.

**Comment by thiendangit** [comment]
@nguyenthanhtruongntt85  fork this for my quickly project, this is not the official project and now i don't have time to support for you. if you have solution please create a pr for me

**Comment by nguyenthanhtruongntt85** [comment]
> @nguyenthanhtruongntt85 i fork this for my quickly project, this is not the official project and now i don't have time to support for you. if you have solution please create a pr for me

ok, thanks!
